import {describe,expect,it,vi} from 'vitest';
import {clearLocalReview,exportFilename,exportReviewFile,filterQueue,importedReviewErrors,loadLocalReviews,mergeImports,previewImport,progressCounts,publishedState,saveLocalReviews,type GreekReview,type QueueItem} from '../src/greek-review';

const item=(id:string,overrides:Partial<QueueItem>={}):QueueItem=>({candidateId:id,bookDetailFile:'books/ISA.json',queueReasons:['ubs-overlap'],source:{reference:'ISA.1.1',book:'ISA',displayName:'Isaiah',corpusCategory:'protocanonical',directionalEligibility:'eligible'},target:{reference:'ROM.1.1',book:'ROM'},adjustedSimilarityScore:.7,rawSimilarityScore:.7,similarityCategory:'high',ubsOverlap:true,formulaic:false,...overrides});
const review=(id:string,overrides:Partial<GreekReview>={}):GreekReview=>({candidateId:id,algorithmVersion:'v1',reviewStatus:'reviewed',reviewKind:'expert',relationshipType:'possible-echo',reviewerConfidence:3,chronologyConfidence:'direction-probable',independenceGroup:'',notes:'',supportingSources:[],reviewedAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z',...overrides});

describe('Greek review browser state',()=>{
  it('serializes, autosaves, loads, and clears local reviews',()=>{const storage={value:'',getItem:vi.fn(()=>storage.value),setItem:vi.fn((_key:string,value:string)=>{storage.value=value})};saveLocalReviews(storage,[review('a')]);expect(storage.setItem).toHaveBeenCalledOnce();expect(loadLocalReviews(storage)).toHaveLength(1);expect(clearLocalReview(loadLocalReviews(storage),'a')).toEqual([])});
  it('previews imports without changing local state',()=>{const local=[review('a')],incoming={schemaVersion:2,layer:'greek-reuse',algorithmVersion:'v1',datasetGeneratedAt:'2026-01-01T00:00:00Z',reviews:[review('a',{notes:'changed'}),review('b'),review('unknown'),review('c',{algorithmVersion:'old'})]};const preview=previewImport(incoming,local,new Set(['a','b','c']),'v1');expect(preview).toMatchObject({newReviews:2,updatedReviews:1,conflicts:1,unknownCandidateIds:['unknown'],algorithmVersionMismatches:['c']});expect(local[0]?.notes).toBe('')});
  it('rejects malformed import records before merge',()=>{const malformed={schemaVersion:2,layer:'greek-reuse',algorithmVersion:'v1',datasetGeneratedAt:'2026-01-01T00:00:00Z',reviews:[{...review('a'),relationshipType:'invalid'}]} as unknown as Parameters<typeof importedReviewErrors>[0];expect(importedReviewErrors(malformed).join(' ')).toContain('invalid relationshipType')});
  it('handles all import conflict choices',()=>{const old=review('a'),newer=review('a',{notes:'new',updatedAt:'2026-02-01T00:00:00.000Z'});expect(mergeImports([old],[newer],'local')[0]?.notes).toBe('');expect(mergeImports([old],[newer],'imported')[0]?.notes).toBe('new');expect(mergeImports([old],[newer],'latest')[0]?.notes).toBe('new')});
  it('builds export structure and dated filename',()=>{const output=exportReviewFile([review('a')],[item('a')],'v1','2026-01-01T00:00:00Z',new Date('2026-08-03T12:00:00Z'));expect(output).toMatchObject({schemaVersion:2,layer:'greek-reuse',algorithmVersion:'v1',queueCompletion:{reviewed:1}});expect(exportFilename(new Date('2026-08-03T12:00:00Z'))).toBe('greek-reuse-reviews-v2-2026-08-03.json')});
  it('distinguishes published and local records',()=>{expect(publishedState(undefined,undefined)).toBe('No published review');expect(publishedState(undefined,review('a'))).toBe('Published review exists');expect(publishedState(review('a'),review('a'))).toBe('Local draft matches published review');expect(publishedState(review('a',{notes:'draft'}),review('a'))).toBe('Local draft differs from published review')});
  it('counts progress, follow-up, and pending records',()=>{expect(progressCounts([item('a'),item('b'),item('c')],[review('a',{followUp:true}),review('b',{reviewStatus:'skipped'})])).toEqual({total:3,triaged:0,expertReviewed:1,reviewed:1,pending:1,skipped:1,followUp:1,completionPercentage:67})});
  it('filters queue across algorithm and draft fields',()=>{const queue=[item('a'),item('b',{ubsOverlap:false,formulaic:true,similarityCategory:'medium',queueReasons:['formulaic-audit'],source:{reference:'GEN',book:'GEN',displayName:'Genesis',corpusCategory:'protocanonical',directionalEligibility:'eligible'},target:{reference:'MAT',book:'MAT'}})];expect(filterQueue(queue,[review('b',{relationshipType:'uncertain',followUp:true})],{reviewStatus:'reviewed',relationshipType:'uncertain',ubsOverlap:'false',formulaic:'true',sourceBook:'GEN',targetBook:'MAT',queueReason:'formulaic-audit',followUpOnly:true})).toEqual([queue[1]])});
});
