import {describe,expect,it} from 'vitest';import {transliterateGreek,evidenceSummary,suggestedHandling} from '../src/greek-assistance';import {mappingFor,parseUsfm} from '../scripts/brenton-assistance.mjs';import {migrateV1Reviews,REVIEW_STORAGE_KEY,REVIEW_STORAGE_V1_BACKUP_KEY,REVIEW_STORAGE_V1_KEY,loadLocalReviews,TRIAGE_OUTCOMES} from '../src/greek-review';
describe('English review assistance',()=>{it('parses USFM without fuzzy book inference',()=>expect(parseUsfm('\\id GEN\n\\c 1\n\\v 1 In the beginning.')).toEqual({id:'GEN',verses:{'1:1':'In the beginning.'}}));it('uses explicit Kingdoms and Psalm mappings',()=>{expect(mappingFor('1SAM').usfmBook).toBe('1SA');expect(mappingFor('1KGS').usfmBook).toBe('1KI');expect(mappingFor('PS').notes).toContain('numbering');expect(mappingFor('Genesis').status).toBe('unknown')});it('rejects unsafe recensions',()=>{expect(mappingFor('DAN').status).toBe('unsupported');expect(mappingFor('TOBS').status).toBe('unsupported')});it('transliterates accents while preserving boundaries',()=>{expect(transliterateGreek('Ἐν ἀρχῇ, λόγος')).toBe('En archē, logos');expect(transliterateGreek('λογος')).toBe('logos')});it('creates factual summaries and transparent suggestions',()=>{const c={sharedLemmas:['a'],sharedRareLemmas:[],exactNgrams:[],adjustedSimilarityScore:.5,formulaicPenalty:0,overlapsUbsGroup:true};expect(evidenceSummary(c)).toContain('adjusted score is 0.500');expect(suggestedHandling(c,'complete','eligible')).toContain('external support');expect(suggestedHandling(c,'unavailable','eligible')).toBe('Greek-expert review required.')});it('defines six triage outcomes',()=>expect(TRIAGE_OUTCOMES).toHaveLength(6));it('migrates and backs up v1 local drafts',()=>{const values=new Map([[REVIEW_STORAGE_V1_KEY,JSON.stringify([{candidateId:'a'}])]]),storage={getItem:(k:string)=>values.get(k)||null,setItem:(k:string,v:string)=>void values.set(k,v)};expect(loadLocalReviews(storage)[0]?.reviewKind).toBe('expert');expect(values.has(REVIEW_STORAGE_KEY)).toBe(true);expect(values.has(REVIEW_STORAGE_V1_BACKUP_KEY)).toBe(true);expect(migrateV1Reviews([{candidateId:'a'}])[0]?.reviewKind).toBe('expert')})});

describe('Brenton USFM note regression',()=>{
 it('removes complete cross-reference and footnote containers, including internal markers',()=>{const parsed=parseUsfm('\\id ISA\n\\c 6\n\\v 10 \\x + \\xo 6:10 \\xt Mat. 13. 15; Mark 4. 12.\\x* For the heart \\f + \\fr 6:10 \\ft a footnote \\fq quoted\\f* of this people.');expect((parsed.verses as Record<string,string>)['6:10']).toBe('For the heart of this people.')});
 it('retains text in character formatting markers and removes multiple notes',()=>{const parsed=parseUsfm('\\id GEN\n\\c 1\n\\v 1 \\add Truly\\add* text\\x + \\xt Gen. 1:2\\x*, \\nd LORD\\nd* and \\it words\\it*\\fe + \\ft end note\\fe*.');expect((parsed.verses as Record<string,string>)['1:1']).toBe('Truly text, LORD and words.')});
 it('keeps the normalized Isaiah 6:10 fixture free of leaked metadata',async()=>{const data=(await import('../data/normalized/brenton-verses.json')).default;expect(data.books.ISA['6:10']).toMatch(/^For the heart/);expect(data.books.ISA['6:10']).not.toMatch(/Mat\.|Mark\.|\\x/) });
 it('contains no residual note markers in normalized verses',async()=>{const {residualUsfmArtifact}=await import('../scripts/brenton-assistance.mjs');const data=(await import('../data/normalized/brenton-verses.json')).default;expect(Object.values(data.books).flatMap(Object.values).filter(residualUsfmArtifact)).toEqual([])});
});
