import {describe,expect,it} from 'vitest';
import {normalizeGreek,normalizeGreekLemma} from '../scripts/normalize-greek.mjs';
import {alignTextFabricFeatures,parseTextFabricFeature} from '../scripts/parse-textfabric.mjs';
import {parseNestleMorph,parseOsisReference} from '../scripts/parse-nestle1904.mjs';
import {buildPassageWindows,groupGreekVerses} from '../scripts/build-greek-windows.mjs';
import {buildLemmaIndex,inverseDocumentFrequencies,retrieveCandidates} from '../scripts/index-greek-lemmas.mjs';
import {exactNgrams,longestCommonSubsequence,scoreGreekCandidate} from '../scripts/score-greek-candidates.mjs';
import {clusterGreekCandidates} from '../scripts/cluster-greek-candidates.mjs';
import {filterGreekRows} from '../src/greek-reuse-view';
import {buildGreekRankings,projectGreekVerses} from '../scripts/greek-reuse-rankings.mjs';

describe('Greek normalization',()=>{it('removes accents, breathings, punctuation, apostrophes, elision, and normalizes final sigma',()=>{expect(normalizeGreek('Ἐν, ἀρχῇ· λόγος!')).toBe('εναρχηλογοσ');expect(normalizeGreek('λόγος')).toBe(normalizeGreek('λόγος'));expect(normalizeGreekLemma('καθ’')).toBe('καθ')})});
describe('Text-Fabric parsing',()=>{it('supports metadata, dense, empty, escaped, sparse, and ranges',()=>{const dense=parseTextFabricFeature('@valueType=str\n\nα\n\nβ\\tγ');expect(dense.metadata.valueType).toBe('str');expect(dense.values.get(1)).toBe('α');expect(dense.values.get(2)).toBe('');expect(dense.values.get(3)).toBe('β\tγ');const sparse=parseTextFabricFeature('@valueType=str\n\n2-4\tλόγος\n7\tθεός');expect(sparse.values.get(3)).toBe('λόγος');expect(sparse.values.get(7)).toBe('θεός')});it('validates compatible aligned coverage',()=>{const feature={metadata:{},values:new Map([[1,'x'],[2,'y']]),sparse:false};expect(alignTextFabricFeatures({book:feature,word:feature},['book','word'])).toHaveLength(2);expect(()=>alignTextFabricFeatures({book:feature},['book','word'])).toThrow(/Missing required/)})});
describe('Nestle morphology',()=>{it('parses seven columns and OSIS references',()=>{const parsed=parseNestleMorph('Matt.1.1\tΒίβλος\tN\tN-NSF\t976\tβίβλος\tβιβλος');expect(parsed.words[0]).toMatchObject({book:'MAT',chapter:1,verse:1,lemma:'βίβλος'});expect(parseOsisReference('Rom.1.17')).toMatchObject({book:'ROM',chapter:1,verse:17});expect(parseNestleMorph('bad\trow').invalid).toHaveLength(1)})});
describe('windows, retrieval, scoring, and clustering',()=>{const words=[{book:'LEV',chapter:19,verse:18,surface:'ἀγαπήσεις',normalized:'αγαπησεις',lemma:'ἀγαπάω',sp:'verb'},{book:'LEV',chapter:19,verse:18,surface:'πλησίον',normalized:'πλησιον',lemma:'πλησίον',sp:'noun'},{book:'LEV',chapter:19,verse:18,surface:'σεαυτόν',normalized:'σεαυτον',lemma:'σεαυτόν',sp:'pronoun'},{book:'LEV',chapter:19,verse:19,surface:'νόμον',normalized:'νομον',lemma:'νόμος',sp:'noun'},{book:'TOB',chapter:1,verse:1,surface:'λόγος',normalized:'λογος',lemma:'λόγος',sp:'noun'}],verses=groupGreekVerses(words,'greek-reuse-lxx'),windows=buildPassageWindows(verses,[1,2]);type GreekWindowFixture=(typeof windows)[number];it('creates passage windows without crossing books',()=>{expect(windows.some((window:GreekWindowFixture)=>window.verseIds.some((id:string)=>id.includes('LEV'))&&window.verseIds.some((id:string)=>id.includes('TOB')))).toBe(false);expect(windows.some((window:GreekWindowFixture)=>window.verseIds.length===2)).toBe(true)});it('uses an inverted index and transparent bounded scores',()=>{const source=windows[0]!,target={...source,id:'greek-reuse-nt:MAT.22.39',book:'MAT'},idf=inverseDocumentFrequencies(windows),index=buildLemmaIndex(windows);expect(retrieveCandidates(target,index,idf,{minimumSharedContentLemmas:3,maxRetrievedSourcesPerTarget:10})).not.toHaveLength(0);const score=scoreGreekCandidate(source,target,idf);expect(score.score).toBeGreaterThanOrEqual(0);expect(score.score).toBeLessThanOrEqual(1);expect(score.sharedLemmas).toHaveLength(3);expect(exactNgrams(source.surfaceTokens,target.surfaceTokens)).not.toHaveLength(0);expect(longestCommonSubsequence(['a','b'],['b','a'])).toBe(1)});it('penalizes function-word-only evidence and clusters nested overlap deterministically',()=>{const source=windows[0]!,target={...source,id:'nt'},idf=new Map(source.lemmaTokens.map((token:string)=>[token,1])),normal=scoreGreekCandidate(source,target,idf),penalized=scoreGreekCandidate({...source,lemmaTokens:['και']},{...target,lemmaTokens:['και']},new Map([['και',1]]),{stopwords:new Set(['και'])});const proper=scoreGreekCandidate({...source,lemmaTokens:['δαυιδ'],posTokens:['proper']},{...target,lemmaTokens:['δαυιδ'],posTokens:['proper']},new Map([['δαυιδ',5]]));expect(penalized.score).toBeLessThan(normal.score);expect(proper.penalties.properNameOnly).toBeGreaterThan(0);expect(clusterGreekCandidates([normal,{...normal,id:'alternative',score:normal.score-.01}])).toHaveLength(1);expect(normal.id).toBe(scoreGreekCandidate(source,target,idf).id)})});
it('filters Greek passage counts without exceeding the total',()=>{const rows=[{id:'a',book:'PSA',originalReference:'PSA 109:1',text:'ειπεν',rank:1,highCount:1,mediumOrHigherCount:2,distinctNtBookCount:1,scoreSum:1.4,maximumScore:.8,ubsOverlapCount:1,exactNgramOccurrenceCount:1,maximumSharedContentLemmaCount:3,targetBooks:['MAT'],candidates:['c'],startChapter:109,startVerse:1,endChapter:109,endVerse:1}];expect(filterGreekRows(rows,{search:'109',book:'PSA',targetBook:'MAT',minimumScore:.7,ubsStatus:'yes',similarityCategory:'high',minimumSharedContentLemmas:3,exactNgramRequired:true})).toHaveLength(1);expect(filterGreekRows(rows,{search:'',book:'',targetBook:'',minimumScore:.9,ubsStatus:'',similarityCategory:'',minimumSharedContentLemmas:0,exactNgramRequired:false})).toHaveLength(0)});
describe('source verse projection',()=>{
 const metadata={directionalEligibility:'eligible',corpusCategory:'protocanonical',displayName:'Leviticus'},source=(id:string)=>({id,book:'LEV',bookOrder:0,startChapter:19,startVerse:18,endChapter:19,endVerse:19,verseIds:['greek-reuse-lxx:LEV.19.18','greek-reuse-lxx:LEV.19.19'],originalWords:['ἀγαπήσεις','νόμον'],surfaceTokens:['αγαπησεισ','νομον'],lemmaTokens:['αγαπαω','νομοσ'],posTokens:['verb','noun'],bookMetadata:metadata}),target=(id='greek-reuse-nt:MAT.22.39',book='MAT')=>({id,book,verseIds:[id]}),candidate=(id:string,sourceId:string,options:Record<string,unknown>={})=>({id,source:source(sourceId),target:target(),score:.8,rawSimilarityScore:.8,formulaicCategories:[],formulaicOnly:false,overlapsUbsGroup:id==='c1',exactNgrams:['x'],sharedLemmas:['αγαπαω','νομοσ'],sharedRareLemmas:['αγαπαω'],thresholds:{high:.7,medium:.5},...options});
 it('projects filter metadata, scores, deduplicated targets, and individual verse text',()=>{const c1=candidate('c1','p1'),c2=candidate('c2','p2',{score:.75}),formulaic=candidate('formulaic','p3',{target:target('greek-reuse-nt:ROM.1.1','ROM'),score:.9,formulaicOnly:true,formulaicCategories:['doxology']}),clusters=[c1,c2,formulaic].map(representative=>({representative})),rankings=buildGreekRankings(clusters,{high:.7,medium:.5}),before=structuredClone(rankings),verseRecords=[{id:'greek-reuse-lxx:LEV.19.18',words:[{surface:'ἀγαπήσεις'}]},{id:'greek-reuse-lxx:LEV.19.19',words:[{surface:'νόμον'}]}],projected=projectGreekVerses(rankings,new Map([[c1.id,c1],[c2.id,c2],[formulaic.id,formulaic]]),{high:.7,medium:.5},verseRecords);
  expect(rankings).toEqual(before);expect(rankings.map((row:{rank:number})=>row.rank)).toEqual([1,1,3]);expect(projected).toHaveLength(2);
  expect(projected.map((row:{text:string})=>row.text)).toEqual(['ἀγαπήσεις','νόμον']);expect(projected[0]).toMatchObject({directionalEligibility:'eligible',corpusCategory:'protocanonical',displayName:'Leviticus',scoreSum:.8,maximumScore:.8,highCount:1,mediumOrHigherCount:1,formulaicOnlyCount:1,sourcePassageCount:3,ntOccurrenceCount:1,distinctNtBookCount:1});expect(projected[0].candidates).toHaveLength(2);
  expect(filterGreekRows(projected,{search:'',book:'',targetBook:'',minimumScore:0,ubsStatus:'',similarityCategory:'',minimumSharedContentLemmas:0,exactNgramRequired:false,sourceCorpus:'eligible',formulaicStatus:'nonformulaic'})).toHaveLength(2)
 });
});
