import {describe,expect,it} from 'vitest';
import {validateReviewData} from '../scripts/greek-review-validation.mjs';
const base={schemaVersion:2,layerId:'greek-reuse',algorithmVersion:'v1',datasetGeneratedAt:'2026-01-01T00:00:00Z',reviewSetVersion:2,reviews:[{candidateId:'known',algorithmVersion:'v1',reviewStatus:'reviewed',reviewKind:'expert',relationshipType:'possible-echo',reviewerConfidence:4,chronologyConfidence:'direction-probable',independenceGroup:'',notes:'',supportingSources:[{citation:'Author, Work, 1',url:'',notes:''}],reviewedAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'}]};
describe('published review validation',()=>{
  it('accepts the schema offline',()=>expect(validateReviewData(base,{candidateIds:new Set(['known']),algorithmVersion:'v1'})).toEqual([]));
  it('rejects invalid enums and unknown candidates',()=>{const value=structuredClone(base);value.reviews[0]!.relationshipType='opinion';value.reviews[0]!.candidateId='missing';const errors=validateReviewData(value,{candidateIds:new Set(['known']),algorithmVersion:'v1'});expect(errors.join(' ')).toContain('unknown candidate');expect(errors.join(' ')).toContain('invalid relationshipType')});
  it('rejects mismatches unless explicitly historical',()=>{const value=structuredClone(base);value.reviews[0]!.algorithmVersion='old';expect(validateReviewData(value,{candidateIds:new Set(['known']),algorithmVersion:'v1'}).join(' ')).toContain('does not match');(value.reviews[0]! as typeof value.reviews[0]&{historicalAlgorithmVersion:boolean}).historicalAlgorithmVersion=true;expect(validateReviewData(value,{candidateIds:new Set(['known']),algorithmVersion:'v1'})).toEqual([])});
  it('rejects pending published and duplicate records',()=>{const value=structuredClone(base);value.reviews[0]!.reviewStatus='pending';value.reviews.push(structuredClone(value.reviews[0]!));expect(validateReviewData(value,{candidateIds:new Set(['known']),algorithmVersion:'v1'}).join(' ')).toMatch(/pending records|duplicate/) });
});
