import {afterEach,describe,expect,it} from 'vitest';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {buildUbsOverlapIndex,calibrateGreekCandidates,compactCandidate,createMemoryTracker,directMatchingUbsGroups,matchingUbsGroups,processGreekPartitions,readCandidateJsonl} from '../scripts/greek-reuse-pipeline.mjs';
const roots:string[]=[];
afterEach(async()=>{await Promise.all(roots.splice(0).map(path=>rm(path,{recursive:true,force:true})))});
const window=(id:string,book:string,verses:string[])=>({id,book,nativeBook:book,bookOrder:0,startChapter:1,startVerse:1,endChapter:1,endVerse:verses.length,verseIds:verses,originalWords:['λόγος'],surfaceTokens:['λογος'],lemmaTokens:['λογος'],posTokens:['noun'],tokenPositions:[]});
const source=window('greek-reuse-lxx:GEN.1.1-1.1','GEN',['greek-reuse-lxx:GEN.1.1']);
const target=window('greek-reuse-nt:MAT.1.1-1.1','MAT',['greek-reuse-nt:MAT.1.1']);
const event={groupId:'ubs:1',sourcePassage:{bookId:'GEN',verseIds:['quotations:GEN.1.1']},targetPassage:{bookId:'MAT',verseIds:['quotations:MAT.1.1']}};
function candidate(candidateSource=source,candidateTarget=target,score=.8,id='candidate:1'){return {id,source:candidateSource,target:candidateTarget,score,components:{weightedLemmaSimilarity:1},penalties:{lengthDifference:0},sharedLemmas:['λογος'],sharedRareLemmas:['λογος'],matchingPositions:[[0,0]],exactNgrams:['λογος εν αρχη']}}
const retrieve=()=>[{source}];

describe('bounded Greek reuse pipeline',()=>{
  it('matches UBS groups through the index exactly as direct fixture matching',()=>{const index=buildUbsOverlapIndex([event]),value=candidate();expect([...matchingUbsGroups(value,index)]).toEqual([...directMatchingUbsGroups(value,[event])]);expect([...matchingUbsGroups(value,index)]).toEqual(['ubs:1'])});
  it('calibrates deterministically while retaining only one target candidate list',()=>{const targets=Array.from({length:50},(_,index)=>({...target,id:`target:${index}`})),tracker=createMemoryTracker({logger:()=>{}}),run=()=>calibrateGreekCandidates({targetWindows:targets,retrieve,score:(left,right)=>candidate(left,right,.8,`candidate:${right.id}`),ubsIndex:buildUbsOverlapIndex([event]),tracker,progressInterval:10});const first=run(),second=run();expect(first.thresholds).toEqual(second.thresholds);expect(first.scoredPairCount).toBe(50);expect(first.maxRetainedCandidates).toBe(1)});
  it('discards low candidates and clusters overlapping windows inside an NT-book partition',async()=>{const directory=await mkdtemp(join(tmpdir(),'greek-pipeline-'));roots.push(directory);const adjacent={...target,id:'target:adjacent',verseIds:['greek-reuse-nt:MAT.1.1','greek-reuse-nt:MAT.1.2']},john={...target,id:'target:john',book:'JHN',verseIds:['greek-reuse-nt:JHN.1.1']},targets=[target,adjacent,john],result=await processGreekPartitions({targetWindows:targets,retrieve,score:(left,right)=>candidate(left,right,right.book==='JHN'?.1:.8,`candidate:${right.id}`),ubsIndex:buildUbsOverlapIndex([event]),thresholds:{medium:.5,high:.75},tempDirectory:directory,tracker:createMemoryTracker({logger:()=>{}}),limits:{maxRetainedPerPartition:10,maxTempFileBytes:100000},progressInterval:1});expect(result.counts).toMatchObject({scoredPairs:3,lowScoringRawCandidates:1,highRetainedCandidates:2,clusteredRepresentatives:1,nestedAlternativesRemoved:1});expect(result.summaries).toHaveLength(1);expect(result.lowAudit.sample).toHaveLength(1);expect(await readCandidateJsonl(join(directory,'GEN.jsonl'))).toHaveLength(1)});
  it('keeps different NT books in separate partition-local clusters',async()=>{const directory=await mkdtemp(join(tmpdir(),'greek-partitions-'));roots.push(directory);const john={...target,id:'target:john',book:'JHN',verseIds:['greek-reuse-nt:JHN.1.1']},result=await processGreekPartitions({targetWindows:[target,john],retrieve,score:(left,right)=>candidate(left,right,.8,`candidate:${right.book}`),ubsIndex:buildUbsOverlapIndex([event]),thresholds:{medium:.5,high:.75},tempDirectory:directory,tracker:createMemoryTracker({logger:()=>{}}),limits:{maxRetainedPerPartition:10,maxTempFileBytes:100000}});expect(result.summaries).toHaveLength(2);expect(result.counts.clusteredRepresentatives).toBe(2)});
  it('produces deterministic summaries when target partitions arrive in different orders',async()=>{const firstDirectory=await mkdtemp(join(tmpdir(),'greek-order-a-')),secondDirectory=await mkdtemp(join(tmpdir(),'greek-order-b-'));roots.push(firstDirectory,secondDirectory);const john={...target,id:'target:john',book:'JHN',verseIds:['greek-reuse-nt:JHN.1.1']},options={retrieve,score:(left:typeof source,right:typeof target)=>candidate(left,right,.8,`candidate:${right.book}`),ubsIndex:buildUbsOverlapIndex([event]),thresholds:{medium:.5,high:.75},tracker:createMemoryTracker({logger:()=>{}}),limits:{maxRetainedPerPartition:10,maxTempFileBytes:100000}},first=await processGreekPartitions({...options,targetWindows:[target,john],tempDirectory:firstDirectory}),second=await processGreekPartitions({...options,targetWindows:[john,target],tempDirectory:secondDirectory});expect(second.summaries).toEqual(first.summaries)});
  it('creates compact records with frontend lemmas but without scoring-only arrays or per-candidate thresholds',()=>{const compact=compactCandidate(candidate(),new Set(['ubs:1']),'high');expect(compact).toMatchObject({id:'candidate:1',category:'high',overlapsUbsGroup:true});expect(compact.source.lemmaTokens).toEqual(['λογος']);expect(compact.target).not.toHaveProperty('surfaceTokens');expect(compact.source).not.toHaveProperty('tokenPositions');expect(compact).not.toHaveProperty('thresholds')});
  it('bounds simultaneous retention by a partition rather than all stress-fixture pairs',async()=>{const directory=await mkdtemp(join(tmpdir(),'greek-stress-'));roots.push(directory);const targets=Array.from({length:200},(_,index)=>({...target,id:`target:${index}`,book:index<100?'MAT':'JHN'})),sources=Array.from({length:40},(_,index)=>({...source,id:`source:${index}`,verseIds:[`greek-reuse-lxx:GEN.1.${index+1}`]})),result=await processGreekPartitions({targetWindows:targets,retrieve:()=>sources.map(item=>({source:item})),score:(left,right)=>candidate(left,right,.1,`candidate:${left.id}:${right.id}`),ubsIndex:buildUbsOverlapIndex([]),thresholds:{medium:.5,high:.75},tempDirectory:directory,tracker:createMemoryTracker({logger:()=>{}}),limits:{maxRetainedPerPartition:10,maxTempFileBytes:100000}});expect(result.counts.scoredPairs).toBe(8000);expect(result.counts.lowScoringRawCandidates).toBe(8000);expect(result.maxRetainedCandidates).toBe(0);expect(result.summaries).toHaveLength(0)});
  it('reports numeric memory instrumentation',()=>{const logs:string[]=[];const tracker=createMemoryTracker({logger:value=>logs.push(value)});tracker.sample('fixture',{processed:3,retained:1});expect(tracker.metrics().peakRss).toBeGreaterThan(0);expect(JSON.parse(logs[0])).toMatchObject({stage:'fixture',processed:3,retained:1})});
});
