import {afterEach,describe,expect,it} from 'vitest';
import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {OSIS_TO_USFM,discoverNestleMorph,parseNestleMorph,parseOsisReference,validateNestleMorphStructure} from '../scripts/parse-nestle1904.mjs';
const roots:string[]=[];
const row=(reference:string,surface='Βίβλος')=>`${reference}\t${surface}\tN\tN-NSF\t976\tβίβλος\tβιβλος`;
const header='BCV\ttext\tfunc_morph\tform_morph\tstrongs\tlemma\tnormalized';
const productionRow='Matt 1:1\tΒίβλος\tN-NSF\tN-NSF\t976\tβίβλος\tΒίβλος\t';
afterEach(async()=>{await Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true})))});
async function root(){const path=await mkdtemp(join(tmpdir(),'nestle-test-'));roots.push(path);return path}

describe('Nestle1904 reference and row parsing',()=>{
  it('accepts space-colon and legacy dot references including numbered books',()=>{expect(parseOsisReference(' Matt 1:1 ')).toEqual({book:'MAT',chapter:1,verse:1});expect(parseOsisReference('1Cor 13:1')).toEqual({book:'1CO',chapter:13,verse:1});expect(parseOsisReference('2Thess 2:1')).toEqual({book:'2TH',chapter:2,verse:1});expect(parseOsisReference('1John.1.1')).toEqual({book:'1JN',chapter:1,verse:1});expect(parseOsisReference('Matt.1.1')).toEqual({book:'MAT',chapter:1,verse:1})});
  it('rejects unknown and malformed references',()=>{expect(parseOsisReference('Unknown 1:1')).toBeNull();expect(parseOsisReference('Matt.1:1')).toBeNull();expect(parseOsisReference('Matt 0:1')).toBeNull()});
  it('preserves BOM-safe CRLF Greek fields, punctuation, empty fields, and source order',()=>{const parsed=parseNestleMorph(`\uFEFF${row('Matt 1:1','Βίβλος,')}\r\n${row('Mark 1:1','λόγος·').replace('\tN\t','\t\t')}\r\n`);expect(parsed.words).toHaveLength(2);expect(parsed.words[0]).toMatchObject({book:'MAT',surface:'Βίβλος,',sourceOrder:0});expect(parsed.words[1]).toMatchObject({book:'MRK',surface:'λόγος·',functionalMorphology:'',sourceOrder:1})});
  it('skips the verified real header and normalizes a data row trailing empty field',()=>{const parsed=parseNestleMorph(`${header}\n${productionRow}\n`);expect(parsed.words).toHaveLength(1);expect(parsed.invalid).toHaveLength(0);expect(parsed).toMatchObject({physicalNonemptyLines:2,headerLinesSkipped:1,parsedWordRows:1,invalidDataRows:0,trailingEmptyColumnsNormalized:1});expect(parsed.words[0]).toMatchObject({surface:'Βίβλος',functionalMorphology:'N-NSF',formMorphology:'N-NSF',strong:'976',lemma:'βίβλος',normalized:'Βίβλος'})});
  it('recognizes a BOM-prefixed header with an optional trailing empty field',()=>{const parsed=parseNestleMorph(`\uFEFF${header}\t\n${productionRow}`);expect(parsed.words).toHaveLength(1);expect(parsed.headerLinesSkipped).toBe(1);expect(parsed.trailingEmptyColumnsNormalized).toBe(1)});
  it('recognizes the real header and data with CRLF endings',()=>{const parsed=parseNestleMorph(`${header}\r\n${productionRow}\r\n`);expect(parsed.words).toHaveLength(1);expect(parsed.invalid).toHaveLength(0);expect(parsed.headerLinesSkipped).toBe(1)});
  it('accepts both seven fields and exactly one trailing empty field',()=>{const parsed=parseNestleMorph(`${row('Matt 1:1')}\n${row('Mark 1:1')}\t`);expect(parsed.words).toHaveLength(2);expect(parsed.trailingEmptyColumnsNormalized).toBe(1)});
  it('rejects a nonempty eighth field and every nine-field row',()=>{const parsed=parseNestleMorph(`${row('Matt 1:1')}\textra\n${row('Mark 1:1')}\t\textra`);expect(parsed.words).toHaveLength(0);expect(parsed.invalid).toHaveLength(2);expect(parsed.invalid.map(item=>item.reason)).toEqual([expect.stringContaining('found 8'),expect.stringContaining('found 9')])});
  it('parses a headerless first data row',()=>{const parsed=parseNestleMorph(row('Matt 1:1'));expect(parsed.words).toHaveLength(1);expect(parsed.headerLinesSkipped).toBe(0)});
  it('records an unrecognized first line rather than silently treating it as a header',()=>{const parsed=parseNestleMorph(`wrong\ttext\tfunc_morph\tform_morph\tstrongs\tlemma\tnormalized\n${row('Matt 1:1')}`);expect(parsed.words).toHaveLength(1);expect(parsed.invalid).toHaveLength(1);expect(parsed.headerLinesSkipped).toBe(0);expect(parsed.invalid[0]?.reason).toMatch(/Invalid or unknown OSIS reference/) });
  it('requires exactly seven tab-delimited columns',()=>{const parsed=parseNestleMorph('Matt 1:1,not,tabs');expect(parsed.words).toHaveLength(0);expect(parsed.invalid[0]?.reason).toMatch(/7 tab-delimited columns/)})
});

describe('Nestle1904 structural validation and discovery',()=>{
  it('validates all 27 books, coverage, known verses, and deterministic source order',()=>{const books=Object.values(OSIS_TO_USFM).map(book=>String(book??''));if(books.some(book=>!book))throw Error('Expected every Nestle1904 mapping to have a USFM book ID');const known=new Map([['MAT','1:1'],['JHN','1:1'],['ROM','1:1'],['HEB','1:1'],['REV','1:1']]),words=books.map((book,index)=>({book,chapter:Number((known.get(book)||'1:2').split(':')[0]),verse:Number((known.get(book)||'1:2').split(':')[1]),sourceOrder:index,lemma:'λόγος',normalized:'λογος'}));expect(validateNestleMorphStructure({words,invalid:[],nonemptyLines:words.length},{minimumWords:0}).structure.bookCount).toBe(27)});
  it('rejects unknown OSIS books during production validation',()=>{expect(()=>validateNestleMorphStructure({words:[],invalid:[{line:1,reason:'Invalid or unknown OSIS reference: MadeUp 1:1',raw:row('MadeUp 1:1')}],nonemptyLines:1})).toThrow(/invalid or unknown OSIS book references/)});
  it('prefers Nestle1904.csv over recursive candidates',async()=>{const directory=await root();await writeFile(join(directory,'Nestle1904.csv'),row('Matt 1:1'));await writeFile(join(directory,'other.tsv'),row('Mark 1:1'));const found=await discoverNestleMorph(directory,{validate:false});expect(found.path).toBe(join(directory,'Nestle1904.csv'));expect(found.words[0]?.book).toBe('MAT')});
  it('discovers Nestle1904.csv with the production header and trailing-tab row shape',async()=>{const directory=await root();await writeFile(join(directory,'Nestle1904.csv'),`${header}\n${productionRow}\n`);const found=await discoverNestleMorph(directory,{validate:false});expect(found.words).toHaveLength(1);expect(found).toMatchObject({headerLinesSkipped:1,trailingEmptyColumnsNormalized:1,invalidDataRows:0})});
  it('falls back recursively and ignores README and parsing documentation',async()=>{const directory=await root(),nested=join(directory,'nested');await mkdir(nested);await writeFile(join(directory,'README.md'),row('Mark 1:1'));await writeFile(join(directory,'parsing.txt'),row('Luke 1:1'));await writeFile(join(nested,'words.tsv'),row('John 1:1'));const found=await discoverNestleMorph(directory,{validate:false});expect(found.path).toBe(join(nested,'words.tsv'));expect(found.words[0]?.book).toBe('JHN')});
  it('reports inspected files and useful invalid diagnostics',async()=>{const directory=await root();await writeFile(join(directory,'Nestle1904.csv'),'bad\trow');await expect(discoverNestleMorph(directory,{validate:false})).rejects.toThrow(/Files inspected: 1[\s\S]*0 valid[\s\S]*Expected 7 tab-delimited columns/)})
});
