export const FORMULAIC_ANALYSIS_VERSION='greek-formulas-v1';
export const FORMULAIC_SEEDS=[
 {category:'doxology-forever-amen',lemmas:['δοξα','εις','αιων','αιων','αμην']},
 {category:'forever-and-ever-amen',lemmas:['εις','αιων','αιων','αμην']},
 {category:'epistolary-grace',lemmas:['χαρις','υμιν','ειρηνη']},
 {category:'liturgical-amen',lemmas:['αμην','αμην']},
];
const containsSequence=(tokens,sequence)=>tokens.some((_,index)=>sequence.every((token,offset)=>tokens[index+offset]===token));
export function buildFormulaicCorpusStatistics(sourceWindows,targetWindows){const result={};for(const seed of FORMULAIC_SEEDS){const sources=sourceWindows.filter(window=>containsSequence(window.lemmaTokens,seed.lemmas)),targets=targetWindows.filter(window=>containsSequence(window.lemmaTokens,seed.lemmas));result[seed.category]={lxxDocumentFrequency:sources.length,ntDocumentFrequency:targets.length,distinctSourceBooks:new Set(sources.map(window=>window.book)).size,distinctTargetBooks:new Set(targets.map(window=>window.book)).size}}return result}
export function analyzeFormulaicCandidate(candidate,statistics={}){const shared=new Set(candidate.sharedLemmas),categories=FORMULAIC_SEEDS.filter(seed=>containsSequence(candidate.source.lemmaTokens,seed.lemmas)&&containsSequence(candidate.target.lemmaTokens,seed.lemmas)).map(seed=>seed.category),formulaLemmas=new Set(FORMULAIC_SEEDS.filter(seed=>categories.includes(seed.category)).flatMap(seed=>seed.lemmas)),nonformulaicSharedContentLemmaCount=[...shared].filter(lemma=>!formulaLemmas.has(lemma)).length,formulaicOnly=categories.length>0&&nonformulaicSharedContentLemmaCount===0,formulaicEvidenceScore=categories.length?Math.min(1,.5+categories.length*.2):0,formulaicPenalty=formulaicOnly?Math.min(.45,formulaicEvidenceScore*.45):categories.length?Math.min(.2,formulaicEvidenceScore*.2):0,rawSimilarityScore=candidate.score,adjustedSimilarityScore=Math.max(0,rawSimilarityScore-formulaicPenalty),matched=categories.map(category=>statistics[category]||{});return {...candidate,score:adjustedSimilarityScore,rawSimilarityScore,adjustedSimilarityScore,formulaicPenalty,formulaicCategories:categories,formulaicOnly,formulaicEvidenceScore,nonformulaicSharedContentLemmaCount,formulaicStatistics:{lxxDocumentFrequency:Math.max(0,...matched.map(item=>item.lxxDocumentFrequency||0)),ntDocumentFrequency:Math.max(0,...matched.map(item=>item.ntDocumentFrequency||0)),distinctSourceBooks:Math.max(0,...matched.map(item=>item.distinctSourceBooks||0)),distinctTargetBooks:Math.max(0,...matched.map(item=>item.distinctTargetBooks||0))}}}
