import { resolveDataUrl } from './data-url';import type {BookDetail,BookStat,Manifest,Quality,Verse} from './types';export type LayerId='greek-reuse'|'quotations'|'openbible'|'douay';export interface LayerDefinition{id:LayerId;displayName:string;description:string;canonCoverage:number;translation:string;source:string;license:string;manifestPath:string;default:boolean;warning:string}const cache=new Map<string,unknown>();async function json<T>(path:string):Promise<T>{const key=path.replace(/^\/+/,"");if(cache.has(key))return cache.get(key) as T;const response=await fetch(resolveDataUrl(key));if(!response.ok)throw Error(`Data request failed (${response.status}) for ${response.url}`);const value=await response.json() as T;cache.set(key,value);return value}const prefix=(layer:LayerId)=>layer==='douay'?'':`${layer}/`;const rankingsFile=(layer:LayerId)=>layer==='greek-reuse'?'passage-rankings.json':'rankings.json';export const loadLayers=()=>json<LayerDefinition[]>('layers.json');export async function loadLayerCore(layer:LayerId){const p=prefix(layer),[manifest,rawVerses,books,quality]=await Promise.all([json<Manifest>(`${p}manifest.json`),json<Array<Verse&{book?:string;name?:string;connected?:number;incomingScore?:number}>>(`${p}${rankingsFile(layer)}`),json<BookStat[]>(`${p}book-stats.json`),json<Quality>(`${p}data-quality.json`)]);const verses=rawVerses.map(v=>({...v,slug:v.slug||v.book!,modern:v.modern||v.name!,historical:v.historical||v.name!,deuterocanonical:v.deuterocanonical||false,sourceBooks:v.sourceBooks||0}));const normalizedBooks=books.map((b:BookStat&{id?:string;name?:string})=>({...b,slug:b.slug||b.id!,modern:b.modern||b.name!,historical:b.historical||b.name!,deuterocanonical:b.deuterocanonical||false}));return [manifest,verses,normalizedBooks,quality] as const}export const loadBook=(layer:LayerId,book:string)=>json<BookDetail>(`${prefix(layer)}books/${book}.json`);

export const loadQuotationVerseRankings=()=>json<import('./quotation-view').QuotationRow[]>('quotations/verse-rankings.json');

export const loadGreekVerseRankings=()=>json<unknown[]>('greek-reuse/verse-rankings.json');
export const loadGreekCandidateIndex=()=>json<Array<{id:string;book:string}>>('greek-reuse/candidate-index.json');
export const loadGreekReviewQueue=()=>json<import('./greek-review').QueueItem[]|{schemaVersion:number;algorithmVersion:string;datasetGeneratedAt:string;candidates:import('./greek-review').QueueItem[]}>('greek-reuse/review-queue.json');
export const loadPublishedGreekReviews=()=>json<import('./greek-review').ReviewFile>('reviews/greek-reuse-reviews.json');
export const loadGreekReviewAssistance=()=>json<import('./greek-assistance').ReviewAssistance>('greek-reuse/review-assistance.json');
