import {loadBook,loadGreekReviewQueue,loadPublishedGreekReviews} from './data';
import {CHRONOLOGY_CONFIDENCES,RELATIONSHIP_TYPES,REVIEW_POSITION_KEY,REVIEW_STORAGE_KEY,clearLocalReview,exportFilename,exportReviewFile,filterQueue,importedReviewErrors,loadLocalReviews,mergeImports,previewImport,progressCounts,publishedState,saveLocalReviews,type GreekReview,type QueueItem,type ReviewFile} from './greek-review';

type Shell=(content:string)=>void;type Escape=(value:string)=>string;
const labels=(value:string)=>value.split('-').map(x=>x[0]?.toUpperCase()+x.slice(1)).join(' ');
const options=(values:readonly string[],selected?:string)=>values.map(x=>`<option value="${x}" ${x===selected?'selected':''}>${labels(x)}</option>`).join('');

export async function greekReviewPage(shell:Shell,esc:Escape){
  const [rawQueue,publishedFile]=await Promise.all([loadGreekReviewQueue(),loadPublishedGreekReviews()]),queue=('candidates'in rawQueue?rawQueue.candidates:rawQueue) as QueueItem[],algorithmVersion='algorithmVersion'in rawQueue?rawQueue.algorithmVersion:publishedFile.algorithmVersion,datasetGeneratedAt='datasetGeneratedAt'in rawQueue?rawQueue.datasetGeneratedAt:publishedFile.datasetGeneratedAt;
  let reviews=loadLocalReviews(localStorage),filtered=queue,index=Math.min(Number(localStorage.getItem(REVIEW_POSITION_KEY)||0),queue.length-1),candidate:Record<string,unknown>|undefined,pendingImport:ReviewFile|undefined;
  const published=new Map(publishedFile.reviews.map(x=>[x.candidateId,x]));
  shell(`<section class="intro"><p class="eyebrow">Phase E1 · Human review workstation</p><h1>Review automated Greek reuse candidates</h1><p><strong>Reviews made here are stored only in this browser. They are not published until the exported review file is committed to the project.</strong></p><p>Layer D algorithm output, local human-review drafts, and committed published review data remain separate. Classifications are scholarly judgments, not objective facts.</p></section><div id="review-app" class="review-app"><p class="loading">Loading review queue…</p></div>`);
  const root=document.querySelector<HTMLDivElement>('#review-app')!;
  const current=()=>filtered[index];
  const local=()=>reviews.find(x=>x.candidateId===current()?.candidateId);
  const save=(review:GreekReview)=>{reviews=[...reviews.filter(x=>x.candidateId!==review.candidateId),review];saveLocalReviews(localStorage,reviews)};
  const loadCandidate=async()=>{const item=current();if(!item){candidate=undefined;return}localStorage.setItem(REVIEW_POSITION_KEY,String(index));const detail=await loadBook('greek-reuse',item.source.book) as unknown as {candidates:Record<string,unknown>[]};candidate=detail.candidates.find(x=>x.id===item.candidateId)};
  const render=async()=>{await loadCandidate();const item=current(),counts=progressCounts(queue,reviews);if(!item){root.innerHTML='<div class="empty"><h2>No candidates match these filters</h2></div>';return}const draft=local(),pub=published.get(item.candidateId),source=candidate?.source as Record<string,unknown>|undefined,target=candidate?.target as Record<string,unknown>|undefined,shared=new Set((candidate?.sharedLemmas||[]) as string[]),greek=(side:Record<string,unknown>|undefined)=>((side?.originalWords||[]) as string[]).map((word,i)=>shared.has(((side?.lemmaTokens||[]) as string[])[i]||'')?`<mark>${esc(word)}</mark>`:esc(word)).join(' '),components=candidate?.components as Record<string,number>|undefined,penalties=candidate?.penalties as Record<string,number>|undefined;
    root.innerHTML=`<section class="review-progress" aria-label="Queue progress"><b>${counts.total} total</b><span>${counts.reviewed} reviewed</span><span>${counts.pending} pending</span><span>${counts.skipped} skipped</span><span>${counts.followUp} follow-up</span><span>${counts.completionPercentage}% complete</span></section>
    <details class="review-filters"><summary>Queue filters and navigation</summary><form id="review-filters" class="filters"><label>Review status<select name="status"><option value="">All</option>${options(['pending','reviewed','skipped'])}</select></label><label>Relationship<select name="relationship"><option value="">All</option>${options(RELATIONSHIP_TYPES)}</select></label><label>UBS overlap<select name="ubs"><option value="">All</option><option value="true">Yes</option><option value="false">No</option></select></label><label>Similarity<select name="category"><option value="">All</option>${options(['high','medium'])}</select></label><label>Formulaic<select name="formulaic"><option value="">All</option><option value="true">Yes</option><option value="false">No</option></select></label><label>Source book<input name="source"></label><label>Target book<input name="target"></label><label>Queue reason<select name="reason"><option value="">All</option>${options(['ubs-overlap','top-high-non-ubs','medium-stratified-sample','formulaic-audit','chronology-audit','top-ranked-source','inspection-passage'])}</select></label><label>Minimum score<input name="score" type="number" min="0" max="1" step=".01"></label><label><input name="follow" type="checkbox"> Follow-up only</label><button type="submit">Apply filters</button></form><form id="jump-form" class="review-jump"><label>Candidate search<input name="candidate" type="search" placeholder="candidate ID"></label><button>Find</button><label>Jump to queue number<input name="number" type="number" min="1" max="${filtered.length}" value="${index+1}"></label><button>Jump</button><button id="resume" type="button">Resume saved position</button></form></details>
    <nav class="review-nav" aria-label="Candidate navigation"><button id="previous" ${index===0?'disabled':''}>Previous candidate</button><strong>Queue ${index+1} of ${filtered.length}</strong><button id="next" ${index===filtered.length-1?'disabled':''}>Next candidate</button></nav>
    <article class="candidate-review"><header><div><p class="eyebrow">${item.queueReasons.map(esc).join(' · ')}</p><h2>${esc(String(source?.id||item.source.reference))} → ${esc(String(target?.id||item.target.reference))}</h2><code>${esc(item.candidateId)}</code></div><span class="publication-state">${esc(publishedState(draft,pub))}</span></header><div class="parallel-greek"><section><h3>LXX source</h3><p lang="grc">${greek(source)}</p></section><section><h3>NT target</h3><p lang="grc">${greek(target)}</p><p>${esc(String(target?.englishText||'English display text unavailable. No translation has been generated.'))}</p></section></div><dl class="candidate-metrics"><div><dt>Raw / adjusted</dt><dd>${Number(candidate?.rawSimilarityScore||item.rawSimilarityScore).toFixed(3)} / ${Number(candidate?.adjustedSimilarityScore||item.adjustedSimilarityScore).toFixed(3)}</dd></div><div><dt>Category / UBS</dt><dd>${esc(String(candidate?.category||item.similarityCategory))} / ${candidate?.overlapsUbsGroup?'yes':'no'}</dd></div><div><dt>Shared lemmas</dt><dd>${esc(((candidate?.sharedLemmas||[]) as string[]).join(', ')||'—')}</dd></div><div><dt>Shared rare lemmas</dt><dd>${esc(((candidate?.sharedRareLemmas||[]) as string[]).join(', ')||'—')}</dd></div><div><dt>Exact n-grams</dt><dd>${esc(((candidate?.exactNgrams||[]) as string[]).join(' · ')||'—')}</dd></div><div><dt>Score components</dt><dd>${esc(JSON.stringify(components||{}))}</dd></div><div><dt>Applied penalties</dt><dd>${esc(JSON.stringify(penalties||{}))}</dd></div><div><dt>Formulaic evidence</dt><dd>${esc(((candidate?.formulaicCategories||[]) as string[]).join(', ')||'none')} · penalty ${Number(candidate?.formulaicPenalty||0).toFixed(3)}</dd></div><div><dt>Source corpus / direction</dt><dd>${esc(item.source.corpusCategory)} / ${esc(item.source.directionalEligibility)}</dd></div><div><dt>Versification</dt><dd>${esc(JSON.stringify((source?.mappedReference as Record<string,unknown>)||'Native LXX numbering; mapping unavailable'))}</dd></div><div><dt>Alternative windows</dt><dd>${esc(((candidate?.alternativeWindows||[]) as string[]).join(', ')||'none')}</dd></div><div><dt>Provenance</dt><dd>Layer D ${esc(algorithmVersion)} · dataset ${esc(datasetGeneratedAt)} · ${esc(item.bookDetailFile)}</dd></div></dl></article>
    ${pub?`<details class="published-review"><summary>Published review (read-only)</summary><pre>${esc(JSON.stringify(pub,null,2))}</pre>${!draft?'<button id="revise-published">Start local revision from published review</button>':''}</details>`:''}
    <form id="review-form" class="review-form"><h2>Local review draft</h2><p class="local-only">This form autosaves to <code>${REVIEW_STORAGE_KEY}</code>. It does not change published data.</p><label>Relationship classification<select name="relationship" required><option value="">Select…</option>${options(RELATIONSHIP_TYPES,draft?.relationshipType)}</select></label><label>Reviewer confidence<select name="confidence" required><option value="">Select…</option>${options(['1','2','3','4','5'],String(draft?.reviewerConfidence||''))}</select></label><label>Chronology confidence<select name="chronology" required><option value="">Select…</option>${options(CHRONOLOGY_CONFIDENCES,draft?.chronologyConfidence)}</select></label><label>Independence group<input name="independence" maxlength="120" value="${esc(draft?.independenceGroup||'')}"></label><label>Review notes<textarea name="notes" maxlength="10000">${esc(draft?.notes||'')}</textarea></label><label>Supporting sources (one per line: citation | URL optional | notes optional)<textarea name="sources">${esc((draft?.supportingSources||[]).map(x=>[x.citation,x.url,x.notes].join(' | ')).join('\n'))}</textarea></label><label>Reviewer label (optional)<input name="reviewer" maxlength="120" value="${esc(draft?.reviewerLabel||'')}"></label><label><input name="followup" type="checkbox" ${draft?.followUp?'checked':''}> Mark for follow-up</label><div class="actions"><button name="action" value="previous">Save and previous</button><button name="action" value="next">Save and next</button><button id="skip" type="button">Skip</button><button id="clear" type="button">Clear review</button></div><p id="autosave-status" role="status" aria-live="polite"></p></form>
    <section class="review-transfer"><h2>Import and export</h2><button id="export">Export reviews</button><label class="file-button">Import reviews<input id="import" type="file" accept="application/json,.json"></label><div id="import-preview" aria-live="polite"></div></section>`;
    wire();
  };
  const move=async(delta:number)=>{index=Math.max(0,Math.min(filtered.length-1,index+delta));await render()};
  const wire=()=>{const form=document.querySelector<HTMLFormElement>('#review-form')!,makeReview=(status:'pending'|'reviewed'|'skipped'= 'pending'):GreekReview=>{const data=new FormData(form),old=local(),now=new Date().toISOString(),sourceLines=String(data.get('sources')||'').split('\n').filter(Boolean).map(line=>{const [citation='',url='',notes='']=line.split('|').map(x=>x.trim());return {citation,url,notes}});return {candidateId:current()!.candidateId,algorithmVersion,reviewStatus:status,relationshipType:(String(data.get('relationship')||old?.relationshipType||'uncertain')) as GreekReview['relationshipType'],reviewerConfidence:Number(data.get('confidence')||old?.reviewerConfidence||1),chronologyConfidence:(String(data.get('chronology')||old?.chronologyConfidence||'direction-unknown')) as GreekReview['chronologyConfidence'],independenceGroup:String(data.get('independence')||''),notes:String(data.get('notes')||''),supportingSources:sourceLines,reviewedAt:old?.reviewedAt||now,updatedAt:now,reviewerLabel:String(data.get('reviewer')||'')||undefined,followUp:data.get('followup')==='on'}};
    let timer=0;form.addEventListener('input',()=>{clearTimeout(timer);timer=window.setTimeout(()=>{save(makeReview('pending'));document.querySelector('#autosave-status')!.textContent='Draft autosaved locally.'},250)});form.addEventListener('submit',event=>{event.preventDefault();const submit=(event as SubmitEvent).submitter as HTMLButtonElement;save(makeReview('reviewed'));void move(submit.value==='previous'?-1:1)});
    document.querySelector('#skip')?.addEventListener('click',()=>{save(makeReview('skipped'));void move(1)});document.querySelector('#clear')?.addEventListener('click',()=>{if(confirm('Clear this browser-local review? Published data will not be changed.')){reviews=clearLocalReview(reviews,current()!.candidateId);saveLocalReviews(localStorage,reviews);void render()}});document.querySelector('#previous')?.addEventListener('click',()=>void move(-1));document.querySelector('#next')?.addEventListener('click',()=>void move(1));
    document.querySelector('#revise-published')?.addEventListener('click',()=>{const value=published.get(current()!.candidateId);if(value){save({...value,updatedAt:new Date().toISOString()});void render()}});
    document.querySelector<HTMLFormElement>('#review-filters')?.addEventListener('submit',event=>{event.preventDefault();const d=new FormData(event.currentTarget as HTMLFormElement);filtered=filterQueue(queue,reviews,{reviewStatus:String(d.get('status')),relationshipType:String(d.get('relationship')),ubsOverlap:String(d.get('ubs')),similarityCategory:String(d.get('category')),formulaic:String(d.get('formulaic')),sourceBook:String(d.get('source')).toUpperCase(),targetBook:String(d.get('target')).toUpperCase(),queueReason:String(d.get('reason')),minimumScore:Number(d.get('score')),followUpOnly:d.get('follow')==='on'});index=0;void render()});
    document.querySelector<HTMLFormElement>('#jump-form')?.addEventListener('submit',event=>{event.preventDefault();const d=new FormData(event.currentTarget as HTMLFormElement),search=String(d.get('candidate')),number=Number(d.get('number'));const found=search?filtered.findIndex(x=>x.candidateId.includes(search)):number-1;if(found>=0){index=found;void render()}});document.querySelector('#resume')?.addEventListener('click',()=>{index=Math.min(Number(localStorage.getItem(REVIEW_POSITION_KEY)||0),filtered.length-1);void render()});
    document.querySelector('#export')?.addEventListener('click',()=>download(exportReviewFile(reviews,queue,algorithmVersion,datasetGeneratedAt),exportFilename()));document.querySelector<HTMLInputElement>('#import')?.addEventListener('change',async event=>{const file=(((event.currentTarget as HTMLInputElement).files)||[])[0];if(!file)return;try{const value=JSON.parse(await file.text()) as ReviewFile;const errors=importedReviewErrors(value);if(errors.length)throw Error(errors.slice(0,5).join('; '));pendingImport=value;const preview=previewImport(value,reviews,new Set(queue.map(x=>x.candidateId)),algorithmVersion);document.querySelector('#import-preview')!.innerHTML=`<p>New ${preview.newReviews}; updated ${preview.updatedReviews}; unchanged ${preview.unchangedReviews}; conflicts ${preview.conflicts}; unknown IDs ${preview.unknownCandidateIds.length}; algorithm mismatches ${preview.algorithmVersionMismatches.length}.</p><p><strong>Export a backup before applying if you may need to restore local drafts.</strong></p><label>Conflict choice<select id="merge-choice"><option value="local">Keep local</option><option value="imported">Use imported</option><option value="latest">Prefer latest updatedAt</option></select></label><button id="confirm-import">Confirm import</button>`;document.querySelector('#confirm-import')?.addEventListener('click',()=>{if(!pendingImport)return;const valid=pendingImport.reviews.filter(x=>queue.some(q=>q.candidateId===x.candidateId)&&x.algorithmVersion===algorithmVersion),choice=(document.querySelector<HTMLSelectElement>('#merge-choice')?.value||'local') as 'local'|'imported'|'latest';reviews=mergeImports(reviews,valid,choice);saveLocalReviews(localStorage,reviews);pendingImport=undefined;void render()})}catch(error){document.querySelector('#import-preview')!.textContent=`Import rejected: ${error instanceof Error?error.message:'Malformed JSON'}`}});
  };
  const download=(value:unknown,filename:string)=>{const url=URL.createObjectURL(new Blob([`${JSON.stringify(value,null,2)}\n`],{type:'application/json;charset=utf-8'})),anchor=document.createElement('a');anchor.href=url;anchor.download=filename;anchor.click();URL.revokeObjectURL(url)};
  await render();
}
