export const REVIEW_STORAGE_KEY='scripture-index:greek-reuse-reviews:v1';
export const REVIEW_POSITION_KEY='scripture-index:greek-reuse-review-position:v1';
export const RELATIONSHIP_TYPES=['explicit-quotation','close-verbal-reuse','probable-allusion','possible-echo','formulaic-common-expression','unrelated-false-positive','uncertain'] as const;
export const CHRONOLOGY_CONFIDENCES=['direction-certain','direction-probable','direction-disputed','shared-earlier-tradition-possible','direction-unknown'] as const;
export type ReviewStatus='pending'|'reviewed'|'skipped';
export interface SupportingSource{citation:string;url:string;notes:string}
export interface GreekReview{candidateId:string;algorithmVersion:string;reviewStatus:ReviewStatus;relationshipType:typeof RELATIONSHIP_TYPES[number];reviewerConfidence:number;chronologyConfidence:typeof CHRONOLOGY_CONFIDENCES[number];independenceGroup:string;notes:string;supportingSources:SupportingSource[];reviewedAt:string;updatedAt:string;reviewerLabel?:string;followUp?:boolean}
export interface ReviewFile{schemaVersion:number;layerId?:string;layer?:string;algorithmVersion:string;datasetGeneratedAt:string;reviewSetVersion?:number;exportedAt?:string;reviews:GreekReview[];queueCompletion?:ReturnType<typeof progressCounts>}
export interface QueueItem{candidateId:string;bookDetailFile:string;queueReasons:string[];source:{reference:string;book:string;displayName:string;corpusCategory:string;directionalEligibility:string};target:{reference:string;book:string};adjustedSimilarityScore:number;rawSimilarityScore:number;similarityCategory:string;ubsOverlap:boolean;formulaic:boolean}

export const serializeReviews=(reviews:GreekReview[])=>JSON.stringify(reviews);
export function loadLocalReviews(storage:Pick<Storage,'getItem'>):GreekReview[]{try{const value=JSON.parse(storage.getItem(REVIEW_STORAGE_KEY)||'[]') as unknown;return Array.isArray(value)?value as GreekReview[]:[]}catch{return []}}
export function saveLocalReviews(storage:Pick<Storage,'setItem'>,reviews:GreekReview[]){storage.setItem(REVIEW_STORAGE_KEY,serializeReviews(reviews))}
export function clearLocalReview(reviews:GreekReview[],candidateId:string){return reviews.filter(x=>x.candidateId!==candidateId)}
export function publishedState(local:GreekReview|undefined,published:GreekReview|undefined){if(!published)return 'No published review';if(!local)return 'Published review exists';const normalize=(value:GreekReview)=>JSON.stringify({...value,updatedAt:undefined,reviewedAt:undefined});return normalize(local)===normalize(published)?'Local draft matches published review':'Local draft differs from published review'}
export function progressCounts(queue:QueueItem[],reviews:GreekReview[]){const map=new Map(reviews.map(x=>[x.candidateId,x])),reviewed=queue.filter(x=>map.get(x.candidateId)?.reviewStatus==='reviewed').length,skipped=queue.filter(x=>map.get(x.candidateId)?.reviewStatus==='skipped').length,followUp=queue.filter(x=>map.get(x.candidateId)?.followUp).length;return {total:queue.length,reviewed,pending:queue.length-reviewed-skipped,skipped,followUp,completionPercentage:queue.length?Math.round((reviewed+skipped)*100/queue.length):0}}
export interface ReviewFilters{reviewStatus?:string;relationshipType?:string;ubsOverlap?:string;similarityCategory?:string;formulaic?:string;sourceBook?:string;targetBook?:string;queueReason?:string;minimumScore?:number;followUpOnly?:boolean}
export function filterQueue(queue:QueueItem[],reviews:GreekReview[],filters:ReviewFilters){const map=new Map(reviews.map(x=>[x.candidateId,x]));return queue.filter(item=>{const review=map.get(item.candidateId),status=review?.reviewStatus||'pending';return (!filters.reviewStatus||status===filters.reviewStatus)&&(!filters.relationshipType||review?.relationshipType===filters.relationshipType)&&(!filters.ubsOverlap||String(item.ubsOverlap)===filters.ubsOverlap)&&(!filters.similarityCategory||item.similarityCategory===filters.similarityCategory)&&(!filters.formulaic||String(item.formulaic)===filters.formulaic)&&(!filters.sourceBook||item.source.book===filters.sourceBook)&&(!filters.targetBook||item.target.book===filters.targetBook)&&(!filters.queueReason||item.queueReasons.includes(filters.queueReason))&&item.adjustedSimilarityScore>=(filters.minimumScore||0)&&(!filters.followUpOnly||review?.followUp)})}
export function previewImport(imported:ReviewFile,local:GreekReview[],candidateIds:Set<string>,algorithmVersion:string){const localMap=new Map(local.map(x=>[x.candidateId,x])),result={newReviews:0,updatedReviews:0,unchangedReviews:0,conflicts:0,unknownCandidateIds:[] as string[],algorithmVersionMismatches:[] as string[]};for(const review of imported.reviews||[]){if(!candidateIds.has(review.candidateId)){result.unknownCandidateIds.push(review.candidateId);continue}if(review.algorithmVersion!==algorithmVersion)result.algorithmVersionMismatches.push(review.candidateId);const old=localMap.get(review.candidateId);if(!old)result.newReviews++;else if(JSON.stringify(old)===JSON.stringify(review))result.unchangedReviews++;else{result.updatedReviews++;result.conflicts++}}return result}
export function importedReviewErrors(file:ReviewFile){const errors:string[]=[];if(file.schemaVersion!==1||(file.layer||file.layerId)!=='greek-reuse'||!Array.isArray(file.reviews))return ['Expected schema version 1 Greek reuse review JSON.'];file.reviews.forEach((review,index)=>{const id=review?.candidateId||`record ${index+1}`;if(!review?.candidateId||typeof review.algorithmVersion!=='string')errors.push(`${id}: candidateId and algorithmVersion are required`);if(!['pending','reviewed','skipped'].includes(review?.reviewStatus))errors.push(`${id}: invalid reviewStatus`);if(!RELATIONSHIP_TYPES.includes(review?.relationshipType))errors.push(`${id}: invalid relationshipType`);if(!Number.isInteger(review?.reviewerConfidence)||review.reviewerConfidence<1||review.reviewerConfidence>5)errors.push(`${id}: reviewerConfidence must be 1–5`);if(!CHRONOLOGY_CONFIDENCES.includes(review?.chronologyConfidence))errors.push(`${id}: invalid chronologyConfidence`);if(!Array.isArray(review?.supportingSources)||review.supportingSources.some(x=>!x||typeof x.citation!=='string'||typeof x.url!=='string'||typeof x.notes!=='string'))errors.push(`${id}: invalid supportingSources`);if(Number.isNaN(Date.parse(review?.reviewedAt))||Number.isNaN(Date.parse(review?.updatedAt)))errors.push(`${id}: invalid timestamps`)});return errors}
export function mergeImports(local:GreekReview[],imported:GreekReview[],choice:'local'|'imported'|'latest'){const map=new Map(local.map(x=>[x.candidateId,x]));for(const review of imported){const old=map.get(review.candidateId);if(!old||choice==='imported'||choice==='latest'&&Date.parse(review.updatedAt)>Date.parse(old.updatedAt))map.set(review.candidateId,review)}return [...map.values()].sort((a,b)=>a.candidateId.localeCompare(b.candidateId))}
export function exportReviewFile(reviews:GreekReview[],queue:QueueItem[],algorithmVersion:string,datasetGeneratedAt:string,now=new Date()):ReviewFile{return {schemaVersion:1,layer:'greek-reuse',algorithmVersion,datasetGeneratedAt,exportedAt:now.toISOString(),reviews,queueCompletion:progressCounts(queue,reviews)}}
export const exportFilename=(date=new Date())=>`greek-reuse-reviews-${date.toISOString().slice(0,10)}.json`;
