export const REVIEW_STORAGE_KEY='scripture-index:greek-reuse-reviews:v2';
export const REVIEW_STORAGE_V1_KEY='scripture-index:greek-reuse-reviews:v1';
export const REVIEW_STORAGE_V1_BACKUP_KEY='scripture-index:greek-reuse-reviews:v1:backup';
export const REVIEW_MIGRATION_NOTICE_KEY='scripture-index:greek-reuse-reviews:v2:migration-notice';
export const REVIEW_POSITION_KEY='scripture-index:greek-reuse-review-position:v1';
export const ASSISTANCE_REFRESH_NOTICE_KEY='scripture-index:greek-reuse-assistance-refresh:2026-e1b';
export const RELATIONSHIP_TYPES=['explicit-quotation','close-verbal-reuse','probable-allusion','possible-echo','formulaic-common-expression','unrelated-false-positive','uncertain'] as const;
export const TRIAGE_OUTCOMES=['externally-supported','contextually-plausible','likely-common-language','likely-unrelated','expert-review-required','cannot-assess'] as const;
export const CHRONOLOGY_CONFIDENCES=['direction-certain','direction-probable','direction-disputed','shared-earlier-tradition-possible','direction-unknown'] as const;
export type ReviewStatus='pending'|'reviewed'|'skipped';export type ReviewKind='triage'|'expert';
export interface SupportingSource{citation:string;url:string;notes:string}
export interface GreekReview{candidateId:string;algorithmVersion:string;reviewStatus:ReviewStatus;reviewKind?:ReviewKind;triageOutcome?:typeof TRIAGE_OUTCOMES[number];triageConfidence?:number;triageNotes?:string;relationshipType?:typeof RELATIONSHIP_TYPES[number];reviewerConfidence?:number;chronologyConfidence?:typeof CHRONOLOGY_CONFIDENCES[number];independenceGroup?:string;notes?:string;supportingSources:SupportingSource[];reviewedAt:string;updatedAt:string;reviewerLabel?:string;followUp?:boolean}
export interface ReviewFile{schemaVersion:number;layerId?:string;layer?:string;algorithmVersion:string;datasetGeneratedAt:string;reviewSetVersion?:number;exportedAt?:string;reviews:GreekReview[];queueCompletion?:ReturnType<typeof progressCounts>}
export interface QueueItem{candidateId:string;bookDetailFile:string;queueReasons:string[];source:{reference:string;book:string;displayName:string;corpusCategory:string;directionalEligibility:string};target:{reference:string;book:string};adjustedSimilarityScore:number;rawSimilarityScore:number;similarityCategory:string;ubsOverlap:boolean;formulaic:boolean}
export const serializeReviews=(reviews:GreekReview[])=>JSON.stringify(reviews);
export function migrateV1Reviews(value:unknown):GreekReview[]{if(!Array.isArray(value))return [];return value.map(x=>({...x,reviewKind:'expert'} as GreekReview))}
export function loadLocalReviews(storage:Pick<Storage,'getItem'|'setItem'>):GreekReview[]{try{const v2=storage.getItem(REVIEW_STORAGE_KEY);if(v2){const parsed=JSON.parse(v2) as unknown;return Array.isArray(parsed)?parsed as GreekReview[]:[]}const raw=storage.getItem(REVIEW_STORAGE_V1_KEY);if(!raw)return [];const parsed=JSON.parse(raw) as unknown;if(!Array.isArray(parsed))return [];const migrated=migrateV1Reviews(parsed);storage.setItem(REVIEW_STORAGE_V1_BACKUP_KEY,raw);storage.setItem(REVIEW_STORAGE_KEY,serializeReviews(migrated));storage.setItem(REVIEW_MIGRATION_NOTICE_KEY,'show');return migrated}catch{return []}}
export function saveLocalReviews(storage:Pick<Storage,'setItem'>,reviews:GreekReview[]){storage.setItem(REVIEW_STORAGE_KEY,serializeReviews(reviews))}
export function clearLocalReview(reviews:GreekReview[],candidateId:string){return reviews.filter(x=>x.candidateId!==candidateId)}
export function publishedState(local:GreekReview|undefined,published:GreekReview|undefined){if(!published)return 'No published review';if(!local)return 'Published review exists';const normalize=(value:GreekReview)=>JSON.stringify({...value,updatedAt:undefined,reviewedAt:undefined});return normalize(local)===normalize(published)?'Local draft matches published review':'Local draft differs from published review'}
export function progressCounts(queue:QueueItem[],reviews:GreekReview[]){const map=new Map(reviews.map(x=>[x.candidateId,x])),triaged=queue.filter(x=>map.get(x.candidateId)?.reviewStatus==='reviewed'&&map.get(x.candidateId)?.reviewKind==='triage').length,expertReviewed=queue.filter(x=>map.get(x.candidateId)?.reviewStatus==='reviewed'&&map.get(x.candidateId)?.reviewKind==='expert').length,skipped=queue.filter(x=>map.get(x.candidateId)?.reviewStatus==='skipped').length,followUp=queue.filter(x=>map.get(x.candidateId)?.followUp).length;return {total:queue.length,triaged,expertReviewed,reviewed:triaged+expertReviewed,pending:queue.length-triaged-expertReviewed-skipped,skipped,followUp,completionPercentage:queue.length?Math.round((triaged+expertReviewed+skipped)*100/queue.length):0}}
export interface ReviewFilters{search?:string;reviewStatus?:string;relationshipType?:string;ubsOverlap?:string;similarityCategory?:string;formulaic?:string;sourceBook?:string;sourceEligibility?:''|'eligible'|'eligible-or-uncertain'|'ineligible';targetBook?:string;queueReason?:string;minimumScore?:number;followUpOnly?:boolean;chronologyScope?:boolean;excludeDerivative?:boolean}
export function filterQueue(queue:QueueItem[],reviews:GreekReview[],filters:ReviewFilters){const map=new Map(reviews.map(x=>[x.candidateId,x])),term=(filters.search||'').trim().toLowerCase();return queue.filter(item=>{const review=map.get(item.candidateId),status=review?.reviewStatus||'pending',searchable=`${item.candidateId} ${item.source.reference} ${item.source.displayName} ${item.target.reference}`.toLowerCase(),eligibilityMatches=!filters.sourceEligibility?true:filters.sourceEligibility==='eligible-or-uncertain'?item.source.directionalEligibility!=='ineligible':item.source.directionalEligibility===filters.sourceEligibility,chronologyMatches=!filters.chronologyScope||item.source.directionalEligibility!=='eligible'||item.source.corpusCategory==='christian-liturgical-or-derivative',derivativeMatches=!filters.excludeDerivative||item.source.corpusCategory!=='christian-liturgical-or-derivative';return (!term||searchable.includes(term))&&(!filters.reviewStatus||status===filters.reviewStatus)&&(!filters.relationshipType||review?.relationshipType===filters.relationshipType)&&(!filters.ubsOverlap||String(item.ubsOverlap)===filters.ubsOverlap)&&(!filters.similarityCategory||item.similarityCategory===filters.similarityCategory)&&(!filters.formulaic||String(item.formulaic)===filters.formulaic)&&(!filters.sourceBook||item.source.book===filters.sourceBook)&&eligibilityMatches&&chronologyMatches&&derivativeMatches&&(!filters.targetBook||item.target.book===filters.targetBook)&&(!filters.queueReason||item.queueReasons.includes(filters.queueReason))&&item.adjustedSimilarityScore>=(filters.minimumScore||0)&&(!filters.followUpOnly||review?.followUp)})}
export type ReviewPreset='high-non-ubs'|'formulaic-audit'|'medium-sample'|'chronology-audit'|'ubs-inspection'|'pending-only';
export function presetFilters(preset:ReviewPreset):ReviewFilters{switch(preset){case'high-non-ubs':return {ubsOverlap:'false',similarityCategory:'high',sourceEligibility:'eligible',excludeDerivative:true};case'formulaic-audit':return {queueReason:'formulaic-audit'};case'medium-sample':return {queueReason:'medium-stratified-sample',similarityCategory:'medium'};case'chronology-audit':return {chronologyScope:true};case'ubs-inspection':return {ubsOverlap:'true'};case'pending-only':return {reviewStatus:'pending'}}}
export function nextMatchingIndex(queue:QueueItem[],matches:QueueItem[],currentIndex:number){if(!matches.length)return currentIndex;const ids=new Set(matches.map(x=>x.candidateId));for(let offset=1;offset<=queue.length;offset++){const next=(currentIndex+offset)%queue.length;if(ids.has(queue[next]!.candidateId))return next}return currentIndex}
export const externalSupportPrefill=()=>({triageOutcome:'externally-supported' as const,triageNotes:'UBS identifies this source-target pair; this records external support without determining the relationship category.',supportingSource:{citation:'UBS Parallel Passages Database',url:'',notes:'Machine-known identification of this pair'}});
export function migrateReviewFile(file:ReviewFile):ReviewFile{return file.schemaVersion===1?{...file,schemaVersion:2,reviewSetVersion:2,reviews:migrateV1Reviews(file.reviews)}:file}
export function previewImport(imported:ReviewFile,local:GreekReview[],candidateIds:Set<string>,algorithmVersion:string){imported=migrateReviewFile(imported);const localMap=new Map(local.map(x=>[x.candidateId,x])),result={newReviews:0,updatedReviews:0,unchangedReviews:0,conflicts:0,unknownCandidateIds:[] as string[],algorithmVersionMismatches:[] as string[]};for(const review of imported.reviews||[]){if(!candidateIds.has(review.candidateId)){result.unknownCandidateIds.push(review.candidateId);continue}if(review.algorithmVersion!==algorithmVersion)result.algorithmVersionMismatches.push(review.candidateId);const old=localMap.get(review.candidateId);if(!old)result.newReviews++;else if(JSON.stringify(old)===JSON.stringify(review))result.unchangedReviews++;else{result.updatedReviews++;result.conflicts++}}return result}
export function importedReviewErrors(raw:ReviewFile){if(![1,2].includes(raw.schemaVersion)||(raw.layer||raw.layerId)!=='greek-reuse'||!Array.isArray(raw.reviews))return ['Expected schema version 1 or 2 Greek reuse review JSON.'];const file=migrateReviewFile(raw),errors:string[]=[];file.reviews.forEach((r,i)=>{const id=r?.candidateId||`record ${i+1}`;if(!r.candidateId||typeof r.algorithmVersion!=='string')errors.push(`${id}: candidateId and algorithmVersion are required`);if(!['pending','reviewed','skipped'].includes(r.reviewStatus))errors.push(`${id}: invalid reviewStatus`);if(!['triage','expert'].includes(r.reviewKind||''))errors.push(`${id}: invalid reviewKind`);if(r.reviewKind==='triage'&&r.reviewStatus==='reviewed'&&(!TRIAGE_OUTCOMES.includes(r.triageOutcome!)||!Number.isInteger(r.triageConfidence)||r.triageConfidence!<1||r.triageConfidence!>5))errors.push(`${id}: completed triage requires outcome and confidence 1–5`);if(r.reviewKind==='expert'&&r.reviewStatus==='reviewed'&&(!RELATIONSHIP_TYPES.includes(r.relationshipType!)||!CHRONOLOGY_CONFIDENCES.includes(r.chronologyConfidence!)))errors.push(`${id}: invalid relationshipType or chronologyConfidence for completed expert review`);if(!Array.isArray(r.supportingSources)||Number.isNaN(Date.parse(r.reviewedAt))||Number.isNaN(Date.parse(r.updatedAt)))errors.push(`${id}: invalid sources or timestamps`)});return errors}
export function mergeImports(local:GreekReview[],imported:GreekReview[],choice:'local'|'imported'|'latest'){const map=new Map(local.map(x=>[x.candidateId,x]));for(const review of imported){const old=map.get(review.candidateId);if(!old||choice==='imported'||choice==='latest'&&Date.parse(review.updatedAt)>Date.parse(old.updatedAt))map.set(review.candidateId,review)}return [...map.values()].sort((a,b)=>a.candidateId.localeCompare(b.candidateId))}
export function exportReviewFile(reviews:GreekReview[],queue:QueueItem[],algorithmVersion:string,datasetGeneratedAt:string,now=new Date()):ReviewFile{return {schemaVersion:2,layer:'greek-reuse',algorithmVersion,datasetGeneratedAt,reviewSetVersion:2,exportedAt:now.toISOString(),reviews,queueCompletion:progressCounts(queue,reviews)}}
export const exportFilename=(date=new Date())=>`greek-reuse-reviews-v2-${date.toISOString().slice(0,10)}.json`;
